"""initial model migration

Revision ID: a0dca7b5a2e2
Revises:
Create Date: 2021-02-28 18:27:16.763902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0dca7b5a2e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('server_name', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('blocked_at', sa.DateTime(), nullable=True),
    sa.Column('blocked', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('server_token')
    # ### end Alembic commands ###
